### ISSUE TITLE
Add more keybinds examples

### ISSUE THREAD

**Issue by Rinyaresu** [RutaTang/quicknote.nvim#1]
Hello, I'm new to neovim and I recently discovered your plugin, I thought it was really cool. However, I'm having trouble creating keymaps. Could you add more examples to the readme file please?

**Comment by RutaTang** [comment]
Hi, thanks for your issue.

Creating keymaps for functions of this plugin is very easy. As you can see from the last line of README, you can use this 
```lua
vim.api.nvim_set_keymap("n", "<leader>p", "<cmd>:lua require('quicknote').NewNoteAtCurrentLine()<cr>",{})
``` 

to map `<leader>p` to call function `NewNoteAtCurrentLine()`.

For other functions of this plugin, for example, for `ToggleMode()`, you can also use `vim.api.nvim_set_keymap` to map to it:

```lua
vim.api.nvim_set_keymap("n", "<leader>t", "<cmd>:lua require('quicknote').ToggleMode()<cr>",{})
```

I think you may want to know how `nvim_set_keymap` works, you can refer to this [Neovim doc](https://neovim.io/doc/user/api.html#nvim_set_keymap())
