### ISSUE TITLE
Off-topic: What terminal are you using in your showcase.gif?

### ISSUE THREAD

**Issue by PhilRunninger** [RutaTang/quicknote.nvim#13]
I had seen it featured in a video a while ago, but I can't remember the name of it. I don't know if I'd like it, but I'd like to try the "comet trail" that follows the cursor. Is it helpful or distracting?

Thanks.

**Comment by RutaTang** [comment]
Hi PhilRunninger,

It's [neovide](https://neovide.dev/), a neovim GUI. I do not normally heavily rely on it and it is not distracting for me. 

If you like to discuss more, you may leave me message here. If not, you may close this issue.

**Comment by PhilRunninger** [comment]
@RutaTang  I gave it a try, but my normal environment is the terminal, so this won't fit my workflow very well. Thanks, anyway.

**Comment by rwmpelstilzchen** [comment]
Then I think you might find [mini.animate](https://github.com/echasnovski/mini.animate) useful :-)
