### ISSUE TITLE
How to handle `No notes found` error gracefully

### ISSUE THREAD

**Issue by onichandame** [RutaTang/quicknote.nvim#17]
When running the command `Telescope quicknote scope=CurrentBuffer` in a file where no note has been created, an error is thrown. I am new to quicknote.nvim so I'm not sure if it is a bug or a mistake in my configuration

![image](https://github.com/RutaTang/quicknote.nvim/assets/23728505/39c2f3d1-41b8-4fc1-9b3e-1ec4b949b611)

**Comment by RutaTang** [comment]
This might be a bug. I will check it or if anyone can check it, really appreciate it.

**Comment by beetol** [comment]
Please see PR #18
