### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Pagliacii** [RutaTang/quicknote.nvim#2]
When I create a new note at the current line, this error message pops up. After I create `.quicknote` folder manually, it works correctly.

```
nvim-data/lazy/quicknote.nvim/lua/quicknote/utils/fs.lua:14: Error: ENOENT: no such file or directory
```

So, how about create the folder automatically at first note creating?

FYI, my configs:

```lua
  {
    "RutaTang/quicknote.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    keys = {
      { "<leader>nlc", "<cmd>:lua require('quicknote').NewNoteAtCurrentLine()<cr>", desc = "Create" },
      { "<leader>nlo", "<cmd>:lua require('quicknote').OpenNoteAtCurrentLine()<cr>", desc = "Open" },
      { "<leader>nld", "<cmd>:lua require('quicknote').DeleteNoteAtCurrentLine()<cr>", desc = "Delete" },
      { "<leader>ncc", "<cmd>:lua require('quicknote').NewNoteAtCWD()<cr>", desc = "Create" },
      { "<leader>nco", "<cmd>:lua require('quicknote').OpenNoteAtCWD()<cr>", desc = "Open" },
      { "<leader>ncd", "<cmd>:lua require('quicknote').DeleteNoteAtCWD()<cr>", desc = "Open" },
      { "<leader>ngc", "<cmd>:lua require('quicknote').NewNoteAtGlobal()<cr>", desc = "Create" },
      { "<leader>ngo", "<cmd>:lua require('quicknote').OpenNoteAtGlobal()<cr>", desc = "Open" },
      { "<leader>ngd", "<cmd>:lua require('quicknote').DeleteNoteAtGlobal()<cr>", desc = "Delete" },
      { "<leader>nLb", "<cmd>:lua require('quicknote').ListNotesForCurrentBuffer()<cr>", desc = "Current buffer" },
      { "<leader>nLc", "<cmd>:lua require('quicknote').ListNotesForCWD()<cr>", desc = "CWD" },
      { "<leader>nLg", "<cmd>:lua require('quicknote').ListNotesForGlobal()<cr>", desc = "Global" },
      { "<leader>nLf", "<cmd>:lua require('quicknote').ListNotesForAFileOrWDInCWD()<cr>", desc = "File or dir" },
      { "<leader>njp", "<cmd>:lua require('quicknote').JumpToPreviousNote()<cr>", desc = "Previous" },
      { "<leader>njn", "<cmd>:lua require('quicknote').JumpToNextNote()<cr>", desc = "Next" },
      { "<leader>nCb", "<cmd>:lua require('quicknote').GetNotesCountForCurrentBuffer()<cr>", desc = "Current buffer" },
      { "<leader>nCc", "<cmd>:lua require('quicknote').GetNotesCountForCWD()<cr>", desc = "CWD" },
      { "<leader>nCg", "<cmd>:lua require('quicknote').GetNotesCountForGlobal()<cr>", desc = "Global" },
      { "<leader>ns", "<cmd>:lua require('quicknote').ToggleNoteSigns()<cr>", desc = "Toggle signs" },
      { "<leader>nEb", "<cmd>:lua require('quicknote').ExportNotesForCurrentBuffer()<cr>", desc = "Current buffer" },
      { "<leader>nEc", "<cmd>:lua require('quicknote').ExportNotesForCWD()<cr>", desc = "CWD" },
      { "<leader>nEg", "<cmd>:lua require('quicknote').ExportNotesForGlobal()<cr>", desc = "Global" },
      { "<leader>nIb", "<cmd>:lua require('quicknote').ImportNotesForCurrentBuffer()<cr>", desc = "Current buffer" },
      { "<leader>nIc", "<cmd>:lua require('quicknote').ImportNotesForCWD()<cr>", desc = "CWD" },
      { "<leader>nIg", "<cmd>:lua require('quicknote').ImportNotesForGlobal()<cr>", desc = "Global" },
    },
  },
```

**Comment by RutaTang** [comment]
Hi, thank you for the issue!

Although I can not reproduce it, I have just checked and made updates to try to fix it. Please let me know if the error is still there.

**Comment by Pagliacii** [comment]
The issue is still exists at this commit d58d582.

```
Error executing luv callback:
.../nvim-data/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...nvim-data/lazy/quicknote.nvim/lua/quicknote/utils/fs.lua:14: Error: ENOENT: no such file or directory: E:\<path>/.quicknote\c9dd62b823880c247b36e4ee5e5f8a388a26ed2d
stack traceback:
	[C]: in function 'error'
	.../nvim-data/lazy/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
	.../nvim-data/lazy/plenary.nvim/lua/plenary/async/async.lua:45: in function <.../nvim-data/lazy/plenary.nvim/lua/plenary/async/async.lua:44>
```

My OS info: Windows 11 Pro 22H2 25357.1

**Comment by RutaTang** [comment]
> The issue is still exists at this commit [d58d582](https://github.com/RutaTang/quicknote.nvim/commit/d58d582c4d886292a41914d44a5a5713f7804e3f).
> 
> ```
> Error executing luv callback:
> .../nvim-data/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...nvim-data/lazy/quicknote.nvim/lua/quicknote/utils/fs.lua:14: Error: ENOENT: no such file or directory: E:\<path>/.quicknote\c9dd62b823880c247b36e4ee5e5f8a388a26ed2d
> stack traceback:
> 	[C]: in function 'error'
> 	.../nvim-data/lazy/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
> 	.../nvim-data/lazy/plenary.nvim/lua/plenary/async/async.lua:45: in function <.../nvim-data/lazy/plenary.nvim/lua/plenary/async/async.lua:44>
> ```
> 
> My OS info: Windows 11 Pro 22H2 25357.1

Hi, I do not have Windows on my side so I am not able to debug it on Windows. It works fine on my Mac and should work fine on Linux. I may try to debug it later (but might be a long time later...) when I have access to Windows.

If you prefer, you may try to submit a PR to fix the issue on Windows. The error is from: `lua > quicknote > utils > fs.lua > MKDirAsync`. It is possibly caused by two factors:

1. The path is not normalized to the standard Windows path.
2. The `mkdir` mode in `async.uv.fs_mkdir(path, tonumber("0777", 8)) ` may not be appropriate for Windows.

**Comment by RutaTang** [comment]
Ok, I know what happened, I will update README. Please check the installation again there.

You should make sure you call the `setup` function in `config`.

**Comment by RutaTang** [comment]
Here is how to install this plugin, make sure you call `setup`:

```lua
require("lazy").setup({
  { "RutaTang/quicknote.nvim", config=function()
        -- you must call setup to let quicknote.nvim works correctly
        require("quicknote").setup({})
  end
  , dependencies = { "nvim-lua/plenary.nvim"} },
})
```

**Comment by RutaTang** [comment]
Please let me know if it works now. If there is no response, I will close this issue a week latter.

**Comment by Pagliacii** [comment]
After I am adding `config = true`, it works correctly. Thx.
