### ISSUE TITLE
Custom sign labels

### ISSUE THREAD

**Issue by ethan-dorta** [RutaTang/quicknote.nvim#6]
Right now, an `N` shows up indicating that there is a note. If the user wanted (or if this could be a default), a Nerd font could be used to have possibly a related emoji show up, or just some other symbol that the user sees fit.

**Comment by RutaTang** [comment]
Hi Flarp, 

Thanks for the endeavor and contribution of chujDK! This feature is implemented now. If you have anything related to this issue, we can discuss more. If not, you can close the issue or I will close it in two weeks if inactive.

**Comment by ethan-dorta** [comment]
Awesome! Thank you!
